M48
; DRILL file {KiCad (6.0.1)} date Sun Jun 19 08:52:12 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-06-19T08:52:12+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X75.0Y-51.0
X86.5Y-141.5
X150.0Y-100.0
X213.5Y-141.5
X225.0Y-51.0
T0
M30
